num_country: 500
num_school: 200
num_major: 500
num_level: 10
list_level: ['Bachelor', 'Fellowship', 'Master', 'PHD', 'Postdoctoral', 'Postgraduate', 'Research', 'Secondary school studies', 'Post-Secondary Education']
list_money: ['Partial Funding', 'Fully Funded' ]  # giá trị học bổng toàn phần hay bán phần
max_year: 2022

weight_country: 0.2
weight_school: 0.05
weight_major: 0.45
weight_level: 0.2
weight_money: 0.05
weight_time: 0.05

num_scholarship_recommned: 6
min_similarity: 0.