num_country: 500
num_school: 200
num_major: 500
num_level: 10
list_level: ['Bachelor', 'Fellowship', 'Master', 'PHD', 'Postdoctoral', 'Postgraduate', 'Research']
list_money: ['Fully Funded', 'Partial Funding']  # giá trị học bổng toàn phần hay bán phần
# time: 